export const CHANGE_SCREEN = "CHANGE_SCREEN";
export const REQ_USER_LOGIN = "REQ_USER_LOGIN";
export const GAME_KEY_SUCCESS = "GAME_KEY_SUCCESS";
export const CREATE_NEW_GAME_INSTANCE = "CREATE_NEW_GAME_INSTANCE";