export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GAME_KEY_SUCCESS = "GAME_KEY_SUCCESS";
export const KEYGAME_FAIL = "KEYGAME_FAIL";
export const NEW_KEY_GAME = "NEW_KEY_GAME";
export const PHASE = "PHASE";
export const CREATE_NEW_GAME_INSTANCE = "CREATE_NEW_GAME_INSTANCE";
export const GAME_PROP = "GAME_PROP"; //i think this type is redundent
export const SERVER_FEEDBACK_TO_ANSWER = "SERVER_FEEDBACK_TO_ANSWER";
export const USER = "USER";
